[package]
name = "blinds_rs"
version = "0.1.0"
authors = ["pwf <aaron.lisman@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.83"
license = "MIT OR Apache-2.0"

[dependencies]
tmc-rs = { version = "0.1.0", path = "../tmc-rs" }
log = { version = "0.4", default-features = false }
esp-idf-svc = "0.52.1"
# The new RMT queue assumes IDF >=5.3; keep compatibility with our pinned 5.1.2.
esp-idf-hal = { version = "0.46.2", features = ["rmt-legacy"] }
anyhow = "1.0.71"

[features]
default = ["std", "esp-idf-svc/native"]
pio = ["esp-idf-svc/pio"]
std = ["alloc", "esp-idf-svc/binstart", "esp-idf-svc/std"]
alloc = ["esp-idf-svc/alloc"]
nightly = ["esp-idf-svc/nightly"]
experimental = ["esp-idf-svc/experimental"]
embassy = ["esp-idf-svc/embassy-sync", "esp-idf-svc/critical-section", "esp-idf-svc/embassy-time-driver"]

[build-dependencies]
embuild = { version = "0.33", features = ["espidf"] }

[profile.release]
opt-level = "s"

[profile.dev]
debug = true
opt-level = "z"
