#[build]
#target = "xtensa-esp32s3-espidf"
#
#[target.xtensa-esp32s3-espidf]
#linker = "ldproxy"
#rustflags = [
#  #"--cfg", "espidf_time64",
#  #"-C", "link-arg=-fuse-ld=lld",
#  #"-C", "linker-plugin-lto",
##  "-C", "default-linker-libraries",
#]
#
#[unstable]
#build-std = ["std", "panic_abort"]
[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
rustflags = ["--cfg", "espidf_time64"]
runner = "espflash flash --monitor --port /dev/ttyACM0"

[unstable]
build-std = ["std", "panic_abort"]

[env]
# Note: these variables are not used when using pio builder (`cargo build --features pio`)
MCU="esp32s3"
ESP_IDF_VERSION = "v5.1.2"
WIFI_SSID = "zerocool"
WIFI_PASS = "nope"
